# Supabase Configuration for Flight Tracker
project_id = "wacrvpraqzvpbsbzvlxp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://myflightfriend.com"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "https://wacrvpraqzvpbsbzvlxp.supabase.co/auth/v1/callback"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions]

[edge_runtime]
policy = "per_worker"